---
title: |
  La enseñanza de la pronunciación: cuatro verdades y unas cuantas mentiras
subtitle: |
  Resumen de Levis (2018) del congreso *Exploring Language Education: Local 
  and Global Perspectives*
author: "Joseph Casillas"
date: "6/28/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Resumen

En una segunda lengua (L2), la pronunciación es uno de los componentes más 
importantes de la comunicación. Sin embargo, se ha dejado de lado (se ha 
ignorado/evitado, etc.) en el mundo de la adquisición de segundas lenguas 
(SLA en inglés), tanto en los modelos teóricos como en la programación 
pedagógica. En los últimos 10-15 años ha habido un intento por parte de los 
investigadores de SLA y los profesores de rectificar la situación actual. Hay 
cada vez más modelos teóricos diseñados específicamente para la adquisición de 
la fonología de una L2 (SLM, PAM-L2, L2LP, entre otros) y los acercamientos 
pedagógicos incluyen actividades de pronunciación con más frecuencia en los 
libros y manuales que van dirigidos al aprendiz. Actualmente, tenemos más 
herramientas a nuestra disposición para ayudarnos a enseñar la pronunciación 
(i.e., estrategias pedagógicas, tecnología del habla, etc.).

## ¿Por qué es importante?

- La pronunciación determina si el aprendiz será entendible
- La pronunciación forma parte de la creación de una identidad en la L2
- La pronunciación es un factor crucial para el éxito del estudiante en el 
extranjero
- Para los inmigrantes...
  - la pronunciación es la primera cosa en la que se fija la gente con la que 
  interactúa 
  - la pronunciación puede representar una barrera a su capacidad de entender 
  a los demás 

## Cuatro verdades

1. La pronunciación representa una habilidad inevitable y esencial para el 
aprendiz
<!--
The new language is power, and pronunciation is an audible symbol of that power, or lack of power. They cannot help but pronounce whenever they speak the new language. How they pronounce fills their thoughts before, during and sometimes after they communicate. And their concerns reflect much that is important for their ability to function, to both make themselves understood and to understand.
-->
2. La enseñanza de la pronunciación funciona
<!--
As language teachers, we typically assume that what we teach makes a difference, whether we teach grammar, vocabulary, pragmatics, listening, reading or writing. But pronunciation teaching is too often thought to be unique in its results, with it outcomes uncertain at best. Thus teachers often avoid it, doing it only in response to errors that irritate or that are so egregious that they cannot be ignored. Such a reactionary approach to pronunciation teaching ignores one of the great truths from research findings: Learners almost always improve when they are instructed with some degree of regularity.
-->
3. La pronunciación es significativa debido a (1) las oportunidades que crea 
para el aprendiz dentro del ambiente de la lengua meta y  (2) a la exclusión 
social que puede crear cuando los aprendices se encuentran con miedo a la hora 
de hablar. 
<!--
We are social beings, and whether others include or exclude us has powerful 
effects on our ability to represent ourselves. 
Pronunciation is often the key that opens the gate to the social world around 
us, and not being able to pronounce acceptably creates barriers to 
self-representation.
-->
4. La enseñanza de la pronunciación encaja bien y naturalmente con la 
enseñanza de otras destrezas relacionadas con la lengua
<!--
When learners read or read aloud, the ability to verbalize the words, phrases 
and sentences encourages comprehension. 
Vocabulary is almost always meant to be spoken, and pronounced, and speaking 
and listening without pronouncing or listening to others pronounce is not 
possible. 
Pronunciation is a servant skill, to be used in the service of other skills, 
and is most effective when this is its role in the language classroom.
-->

<!--
1. Pronunciation is an unavoidable and essential skill for language learners
2. Teaching pronunciation works
3. Pronunciation is socially significant, both in the opportunities it creates 
for language learners in second language settings, and for the social 
exclusion it can create when learners find themselves afraid to speak
4. Teaching pronunciation fits well, and fits naturally, with the teaching of 
other language skills
-->

## Unas cuantas mentiras

- Un aprendiz tardío tiene que hablar como un nativo para tener éxito
<!--
Adult language learners have to sound like native speakers to be successful
-->
- La pronunciación se aprende sola, por lo que no hace falta instrucción 
explícita
<!--
Pronunciation will take care of itself, and it doesn’t need to be taught
-->
- No puedo enseñar la pronunciación porque no soy experto en lingüística
<!--
I cannot teach pronunciation because I am not an expert
-->

\clearpage

# Recursos

## Información

- [www.pronunciationforteachers.com](www.pronunciationforteachers.com)

- Journal of Second Language Pronunciation:  
https://benjamins.com/catalog/jslp

- Pronunciation in Second Language Learning and Teaching Conference:  
http://psllt.org/index.php/psllt/2018

- Información acerca de Levis (2018):  
https://www.isd.su.se/english/exploring-language-education-ele-local-and-global-perspectives/plenary-speakers/john-levis-plenary-speaker-at-ele-1.345019

## Tecnología

- www.ispraak.com

- www.acapela-group.com

- http://soundsofspeech.uiowa.edu/spanish/spanish.html

- www.forvo.com

- Pistas prácticas para la integración de la pronunciación en tus lecciones 
(webinar):  
http://eventcenter.commpartners.com/se/Meetings/Playback.aspx?meeting.id=290652





## Referencias

- Best, C. T., & Tyler, M. D. (2007). Nonnative and second-language speech 
perception. John Benjamins Publishing Company. Amsterdam.

- Flege, J. E. (1995). Second language speech learning: Theory, findings, and 
problems. In W. Strange (Ed.), Speech perception and linguistic experience 
issues in cross-language research (pp. 229–273). Timonium, MD: York Press.

- Escudero, P., & Boersma, P. (2004). Bridging the gap between L2 speech 
perception research and phonological theory. Studies in Second Language 
Acquisition, 26(4), 551–585.

- Levis, J. (2018). Teaching pronunciation: Four truths and a handful of lies. 
*Exploring Language Education: Local and Global Perspectives*. 

